name: new_app
description: Student Profile Book app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0

  # optional helper
  fluttertoast: ^8.2.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
